Repository escapeSparta/escapeSpartaFront, pull requests merged in 2024-08, with the labels that each got.

#8 feature : 로그인 기능구현
  src/App.vue
  src/components/login/Login.vue
  src/components/signup/SignUp.vue
  src/router.js
Labels: feature

#9 feature : #7 메인화면, 카페 검색 페이지 기능 구현
  package-lock.json
  package.json
  src/api/Search.js
  src/components/Header.vue
  src/components/MainTheme.vue
  src/components/SearchStore.vue
  src/components/mypage/main-theme.css
  src/components/mypage/main-theme.html
  src/components/mypage/search-store.css
  src/components/mypage/search-store.html
  src/router.js
Labels: feature

#13 feature : 리뷰 게시판 조회 기능구현
  package-lock.json
  package.json
  src/components/review/ReviewList.vue
  src/router.js
Labels: feature

#17 Feature/12 테마 상세 조회
  src/api/Reservation.js
  src/api/Search.js
  src/components/ThemeInfo.vue
  src/components/예약 진행 화면 (인원수, 결제 방법 선택).html
  src/components/예약 화면.html
  src/router.js
Labels: feature

#19 Feature/16 vuex
  index.html
  src/App.vue
  src/api/Reservation.js
  src/api/Search.js
  src/api/payment.js
  src/axios.js
  src/components/Header.vue
  src/components/auth/Login.vue
  src/components/auth/SignUp.vue
  src/components/login/Login.vue
  src/components/mypage/EditPasswordModal.vue
  src/components/mypage/EditProfileModal.vue
  src/components/mypage/FollowInfo.vue
  src/components/mypage/ReservationInfo.vue
  src/components/mypage/ReviewModal.vue
  src/components/mypage/UserInfo.vue
  src/components/mypage/WithdrawModal.vue
  src/components/mypage/main-theme.css
  src/components/mypage/main-theme.html
  src/components/mypage/search-store.css
  src/components/mypage/search-store.html
  src/components/payment/BookingForm.vue
  src/components/review/ReviewList.vue
  src/components/signup/SignUp.vue
  src/components/예약 진행 화면 (인원수, 결제 방법 선택).html
  src/components/예약 화면.html
  src/main.js
  src/router.js
  src/store/auth.js
  src/store/axios.js
  src/store/index.js
  src/views/About.vue
  src/views/Header.vue
  src/views/MainTheme.vue
  src/views/MyPage.vue
  src/views/Reservation.vue
  src/views/SearchStore.vue
  src/views/ThemeInfo.vue
Labels: feature

#20 Fix/16 검증 로직 재수정
  src/store/axios.js
Labels: fix

#22 Feature/15 cicd nginx.conf 설정 변경
  Dockerfile
  nginx.conf
  package-lock.json
  package.json
  vite.config.js
Labels: bug

#23 Fix/16 css 및 이미지 수정
  src/components/mypage/ReservationInfo.vue
  src/components/payment/BookingForm.vue
  src/components/payment/BookingInfo.vue
  src/views/Reservation.vue
Labels: fix

#31 Feature/25 paging
  docker-compose.yml
  index.html
  src/views/SearchStore.vue
Labels: feature

#34 Feature/32 top stores etc
  .github/workflows/deploy.yml
  src/views/Header.vue
  src/views/ThemeInfo.vue
Labels: fix

#35 Feature/32 top stores etc
  src/components/auth/SignUp.vue
  src/store/axios.js
  src/views/ThemeInfo.vue
Labels: fix

#36 fix : #32 인터셉터 수정
  src/store/axios.js
  src/views/ThemeInfo.vue
Labels: fix

#38 feature/37 카페 상세조회 추가
  README.md
  src/views/MainStore.vue
  src/views/SearchStore.vue
  src/views/ThemeInfo.vue
Labels: feature
